### ISSUE TITLE
Getting Cmake error in ubuntu

### ISSUE THREAD

**Issue by saustar** [alexkarargyris/Caffe_OpenCV_Android_App#1]
HI I am getting following error on my ubuntu machine:
[CMake Warning at cmake/OpenCVDetectCXXCompiler.cmake:95 (message):
  GCC version not detected!
Call Stack (most recent call first):
  CMakeLists.txt:116 (include)

-- Detected version of GNU GCC: 00 (0)
-- Check if the system is big endian
-- Searching 16 bit integer
CMake Error at /usr/local/share/cmake-3.2/Modules/TestBigEndian.cmake:51 (message):
  no suitable type found
Call Stack (most recent call first):
  CMakeLists.txt:529 (test_big_endian)

-- Configuring incomplete, errors occurred!](url)
Any help appreciated!!

**Comment by alexkarargyris** [comment]
@saustar Was there anything you want to share from your experience? Was it a trivial error? Thanks!

**Comment by saustar** [comment]
Yes trivial error . some issue with android ndk path
