### ISSUE TITLE
Error on classification button

### ISSUE THREAD

**Issue by saustar** [alexkarargyris/Caffe_OpenCV_Android_App#2]
Hi I was able to build the app on samsung s4 but when I press CLASSIFY I get following error:
03-15 14:14:32.522 2089-2089/com.example.alexandroskarargyris.myapplication E/cv::error(): OpenCV Error: Unspecified error (FAILED: fs.is_open().Can't open "/sdcard/android-opencv/bvlc_googlenet.prototxt.txt") in bool cv::dnn::ReadProtoFromTextFile(const char_, google::protobuf::Message_), file /home/saurabh/Downloads/opencv_contrib-master/modules/dnn/src/caffe/caffe_io.cpp, line 1077

**Comment by alexkarargyris** [comment]
@saustar Sorry for the late response but you figured out the error?

**Comment by saustar** [comment]
Yes, I was not specifying path for model files properly

**Comment by aseuteurideu** [comment]
@alexkarargyris I got the same problem. I have check and recheck and recheck the path but the problem still exist. Any idea? Is it related to permission? (my caffemodel and prototxt.txt file permission, taken from`adb shell ls -al /sdcard/android-opencv`, are `-rw-rw----` )

The complete output

```
-rw-rw---- root     sdcard_rw 53533754 2016-05-27 17:02 bvlc_googlenet.caffemodel
-rw-rw---- root     sdcard_rw    35816 2016-05-27 17:02 bvlc_googlenet.prototxt.txt
```

**Comment by xae217** [comment]
@kalkaneus where you able to solve this?

**Comment by suuhaasa** [comment]
Hey I got the same problem as well. The name of the file is just bvlc_googlenet.prototxt not bvlc_googlenet.prototxt.txt

**Comment by suuhaasa** [comment]
also I used dnn::Blob inputBlob = dnn::Blob::fromImages(img); instead of dnn::Blob inputBlob = dnn::Blob(img);
