### ISSUE TITLE
can not use dnn

### ISSUE THREAD

**Issue by niewuya** [alexkarargyris/Caffe_OpenCV_Android_App#4]
hello,thinks for your project.When I use nkd to build the project,I get the error in the fellow :
 /home/sgxu/linphone/android-ndk-r10c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: /home/sgxu/Downloads/Smartface/app/src/main/obj/local/armeabi-v7a/objs/MyLib/com_example_alexandroskarargyris_myapplication_NativeClass.o: in function Java_com_jeocloud_st_smartface_NativeClass_getStringFromNative(_JNIEnv_, _jobject_):/home/sgxu/Downloads/Smartface/app/src/main/jni/com_example_alexandroskarargyris_myapplication_NativeClass.cpp:67: error: undefined reference to 'cv::dnn::createCaffeImporter(cv::String const&, cv::String const&)'.

I can't find out the reason,but I think it could not navigate the lopencv_dnn.a to the project.

**Comment by alexkarargyris** [comment]
@niewuya Yes I think you are right. Have you made sure that that OpenCV with DNN module has been built: https://github.com/alexkarargyris/Caffe_OpenCV_Android_App#1-create-opencv-gradle-project  I know the whole procedure can be very tricky. Also check the previous [step](https://github.com/alexkarargyris/Caffe_OpenCV_Android_App#3-build-android-opencv-sdk-with-extra-modules-for-android) to make sure your equivalent 'Users/alexandroskarargyris/Downloads/opencv/platforms/build_android_arm/install' is not empty.

**Comment by niewuya** [comment]
OK,I find the problem and deal with it.Thanks a lot.
