### ISSUE TITLE
Java Folder Not Generating

### ISSUE THREAD

**Issue by thecoldviews** [alexkarargyris/Caffe_OpenCV_Android_App#5]
I follow the same steps, but the java folder under sdk does not generate. Nor does the libopencv_java3. 
I tried the libraries available on the repository, but I get the following on compilation:

Error:error: undefined reference to 'cv::dnn::createCaffeImporter(cv::String const&, cv::String const&)'
Error:error: undefined reference to 'cv::dnn::Net::Net()'
Error:error: undefined reference to 'cv::dnn::Net::~Net()'
Error:error: undefined reference to 'cv::dnn::Net::~Net()'
Error:error: undefined reference to 'cv::dnn::Net::~Net()'
Error:error: undefined reference to 'cv::dnn::Blob::Blob(cv::_InputArray const&, int)'
Error:error: undefined reference to 'cv::dnn::Net::setBlob(cv::String, cv::dnn::Blob const&)'
Error:error: undefined reference to 'cv::dnn::Net::forward()'
Error:error: undefined reference to 'cv::dnn::Net::getBlob(cv::String)'
Error:error: undefined reference to 'cv::dnn::Net::~Net()'

**Comment by thecoldviews** [comment]
I used cmake gui with the android tool chain, which allowed me to create the java file. Still not able to figure out how to connect the static libraries to the jni file.

**Comment by alexkarargyris** [comment]
@jokereactive Sorry I hear you have issues. Can you point me on the tutorial where you are stuck? Thanks!

**Comment by jaderbplima** [comment]
I have the same problem. The folder **java** and the file **libopencv_java3** doesn't generate. I follow all the steps of the tutorial (Requirements), and I'm stuck in **B.1. Create OpenCV Gradle Project**, when I will copy the java folder, which doesn't exists.
Maybe can be a wrong config in my NDK or in Cmake, but I couldn't solve yet.

**Comment by alexkarargyris** [comment]
I am trying to replicate the installation process with the latest NDK and OpenCV versions but it seems that there is some issue with running `cmake_android_arm.sh` . I get the following error: 

`Specified Android native API level 'android-8' is not supported by your
  NDK/toolchain.`

It might be some bug. Anyway I am investigating and I will report here of any findings.

**Comment by thecoldviews** [comment]
I was able to solve this by changing my Android.mk to use the opencv libraries as static libraries instead of shared ones. 
`
OPENCV_LIB_TYPE:=STATIC`

On compilation now, naturally the _opencv_java3.so_ file gets erased from the jni folder on every build, even if you manually keep it there. 

This also forced me to remove 
`System.loadLibrary("opencv_java3");` from my _MainActivity.java_ file since now I am using static OpenCV libraries.

If you find a solution to make it worked with the shared library do let me know here. Using static ones drastically increases the size of the app. 

Please don't close the issue before that. :)

**Comment by surensth** [comment]
1. Set ant path as  ANT_HOME=<path_to_ant_installation_folder >
   eg: export ANT_HOME=/usr/share/apache-ant
2. Set java path as  JAVA_HOME=<path_to_jdk_installation_folder>
   eg: export JAVA_HOME=/opt/JDK

Hope this may help
